apiVersion: v1
kind: Service
metadata:
  name: minio-frontend-vpc-nlb
  namespace: {{ .Values.modelmesh_namespace }}
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
   - name: http
     protocol: TCP
     port: 9000
     targetPort: 9000