apiVersion: v1
kind: Service
metadata:
  name: modelmash-vpc-nlb
  namespace: modelmesh-serving
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "nlb"
spec:
  type: LoadBalancer
  selector:
    modelmesh-service: modelmesh-serving
  ports:
   - name: grpc
     protocol: TCP
     port: 8033
     targetPort: grpc